#pragma once

#define MAX_NETP_POINT ( 0xfffffffeui32 )

const DWORD	NETPY_POINTS_TIME_DURATION = 900;
const DWORD	NETPY_POINTS_TIME_REWARD = 10;
const DWORD NETPY_MAX_SHOPPOINTS = 50000;
const DWORD NETPY_POINTS_REWARD = 7;