<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup Condition="'$(Configuration)'=='Release' And '$(Platform)'=='x64'">
    <RuntimeLibrary>MultiThreaded</RuntimeLibrary>
    <OutDir>$(MSBuildThisFileDirectory)..\Lib\Release_x64\</OutDir>
  </PropertyGroup>
  <ItemDefinitionGroup Condition="'$(Configuration)'=='Release' And '$(Platform)'=='x64'">
    <ClCompile>
      <AdditionalIncludeDirectories>$(MSBuildThisFileDirectory);$(MSBuildThisFileDirectory)plcore;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
    </ClCompile>
  </ItemDefinitionGroup>
</Project>
